services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - mongo
      - postgres

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=plataforma-veiculos

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=plataforma-veiculos
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    command: npm test