services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=plataforma-veiculos

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    command: npm test