name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and start containers using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for MongoDB to be ready
        run: |
          # Aguarda até o MongoDB estar pronto para aceitar conexões
          until nc -zv localhost 27017; do
            echo "Aguardando MongoDB estar pronto..."
            sleep 1
          done

      - name: Install dependencies
        run: |
          # Instala dependências dentro do contêiner
           docker-compose run --rm app npm ci
  
      - name: Clean database before user test
        run: | 
          # Limpa registros do banco de dados
          docker-compose run --rm app node src/db/cleanDB.js

      - name: Perform user testing on the container
        run: |
          # Executa os testes dentro do contêiner da aplicação
          docker-compose run tests npx jest tests/user.test.js

      - name: Clean database before sales test
        run: | 
          # Limpa registros do banco de dados
          docker-compose run --rm app node src/db/cleanDB.js

      - name: Perform sales testing in the container
        run: |
          # Executa os testes dentro do contêiner da aplicação
              docker-compose run tests npx jest tests/sale.test.js

      - name: Clean database before vehicle test
        run: | 
          # Limpa registros do banco de dados
          docker-compose run --rm app node src/db/cleanDB.js    

      - name: Perform vehicle testing in the container
        run: |
          # Executa os testes dentro do contêiner da aplicação
              docker-compose run tests npx jest tests/vehicleInsertUpdate.test.js

      - name: Stop and remove containers
        run: |
          docker-compose down
