name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="curl localhost:27017" --health-timeout=30s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for MongoDB to be ready
        run: |
          # Aguarda até o MongoDB estar pronto para aceitar conexões
          until nc -zv localhost 27017; do
            echo "Aguardando MongoDB estar pronto..."
            sleep 1
          done

      - name: Run tests
        run: npm test
