name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and start containers using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for MongoDB to be ready
        run: |
          # Aguarda até o MongoDB estar pronto para aceitar conexões
          until nc -zv localhost 27017; do
            echo "Aguardando MongoDB estar pronto..."
            sleep 1
          done

      - name: Install dependencies
        run: |
          # Instala dependências dentro do contêiner
           docker-compose run --rm app npm ci
  
      - name: Run all tests
        run: |
          for file in tests/*.test.js; do
            docker-compose run --rm tests npx jest "$file"
          done

      - name: Stop and remove containers
        run: |
          docker-compose down
